# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-12 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='image_attachment',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Images.ImageFiles'),
        ),
    ]
